baseURL: "https://eightpigs.io/"
languageCode: "en-us"
title: "Eightpigs"
theme: "clean"
homepage: "https://eightpigs.io/"
hasCJKLanguage: true
permalinks:
  posts: /:year/:month/:day/:filename

menus:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: archives
      name: Articles
      url: /archives
      weight: 50
    - identifier: about
      name: About
      url: /pages/about
      weight: 100 

params:
  description: A passionate developer who loves to tinker
  keywords: IT,Java,Go,Web,Programmer,Algorithm,Runner
  copyright:
    enable: true
    start: 2014
    end: auto
    name: auto
  socials:
    enable: true
    twitter: eightpigs
    email: eightpigs@outlook.com
    github: eightpigs
  render:
    mathjax: true
    mermaid: true
    flowchart: true
  category:
    inIndex: true
    alias:
      vim: Vim
      linux: Linux
      life: Life
      reading: Reading
      tech: Technology
      hardware: Hardware
      algorithm: Algorithm
      database: Database
      devpractice: Development
      devlang: Programming
      works: Projects
      think: Thoughts
  cc:
    name: by-nc-nd 4.0
    url: https://creativecommons.org/licenses/by-nc-nd/4.0/
  style:
    fontSerif: true
